spring:
  datasource:
    url: jdbc:sqlserver://vishalserver1.database.windows.net:1433;database=AzureDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: Vishaldb
    password: Vishal@538
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect
    
server:
  port: 9988
  
  
  